### ISSUE TITLE
Not working for iOS apps

### ISSUE THREAD

**Issue by sonifex** [deanWombourne/bitrise-step-diawi-upload#11]
I got this error on workflow.

<img width="1094" alt="Screenshot 2020-12-18 at 15 38 00" src="https://user-images.githubusercontent.com/1481877/102632504-42e67f00-4160-11eb-83b8-1626f1b7a60c.png">

**Comment by deanWombourne** [comment]
It looks like you haven't passed in a Diawi api token?

From your screenshot, I think there is a double space between `upload` and your file name, which is where the api token would usually be.

**Comment by sonifex** [comment]
I am passing $BITRISE_IPA_PATH for "ipa/akp/zip file path" variable.
Also adding API token as a secret variable.

**Comment by deanWombourne** [comment]
The path variable seems to be working fine, but it's not picking up the api key for some reason

**Comment by sonifex** [comment]
It worked after recreating the workflow. Thanks.
